<a href="https://colab.research.google.com/github/pizzeman/ds2002-fa26/blob/main/notebooks/05-etl-walmart/2026-10-16%20%E2%80%94%20Walmart%20Warm-Up%20SKU%20Mess%20%E2%80%94%20Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DS2002 · Walmart Warm-Up SKU Mess

**Lab — 2026-10-16 · Fall 2026**  

---

## Lab 08 — Walmart Warm-Up (SKU Mess)

This lab uses the **real midterm data** in `../06-midterm-walmart/data/`. It's a warm-up so you hit the ground running on the project. On Kaggle/Colab, upload the data folder or adjust the path.

*If the file isn't found, the cell falls back to a small inline sample so the notebook still runs.*

In [90]:
import pandas as pd
PATH = '../product_catalog.csv'
try:
    cat = pd.read_csv(PATH)
except FileNotFoundError:
    from io import StringIO
    cat = pd.read_csv(StringIO('sku,product_name,category\nPT-12,pop-tarts strawberry,Breakfast Foods\nSKU#459812,Strawberry Pop-Tart,Breakfast\nPOPTART-STRAW,Pop-Tarts Strawberry,Breakfast'))
cat.head()

,sku,product_name,category,subcategory,unit_cost,supplier,package_size
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack
4,WTR-24,BOTTLED WATER 24PK,Emergency Supplies,Bottled,2.64,Sara Lee,1 pack

### Q1 — How many rows look like Pop-Tart products?

Filter on `product_name` containing `pop`, case-insensitively. Print the count and the matching rows.

In [91]:
# TODO (hint: .str.lower().str.contains('pop'))
pop = cat[cat['product_name'].str.lower().str.contains('pop')]
print(f"Number of pop: {len(pop)}")
pop

Number of pop: 4

,sku,product_name,category,subcategory,unit_cost,supplier,package_size
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack

### Q2 — Which SKUs and names all mean *strawberry* Pop-Tart?

List them. Then note which Pop-Tart rows are **not** strawberry — those must stay separate, and saying so is part of the answer.

In [92]:
# TODO
straw_pop = pop[pop['product_name'].str.lower().str.contains('strawberry')]
not_straw_pop = pop[~pop['product_name'].str.lower().str.contains('strawberry')]
print(f"Number of strawberry pop: {len(straw_pop)}")
print(straw_pop)
print()
print(f"Number of non-strawberry pop: {len(not_straw_pop)}")
not_straw_pop

Number of strawberry pop: 4
             sku          product_name         category subcategory  \
0          PT-12  pop-tarts strawberry  Breakfast Foods         NaN
1     SKU#459812   Strawberry Pop-Tart        Breakfast   Pop-Tarts
2  POPTART-STRAW  Pop-Tarts Strawberry        Breakfast         NaN
3  PT_STRAWBERRY  pop-tarts strawberry        breakfast   Pop-Tarts

   unit_cost           supplier package_size
0       1.93  Johnson & Johnson       4-pack
1       2.26           Roku Inc          4pk
2       2.11           Sara Lee       6 pack
3        NaN         Campbell's       4 pack

Number of non-strawberry pop: 0

Empty DataFrame
Columns: [sku, product_name, category, subcategory, unit_cost, supplier, package_size]
Index: []

**Pop-Tart rows that are a different product:** All of them are strawberry; rows 1-4

### Q3 — Build the mapping

A dict from each variant SKU to one canonical SKU. Then apply it in a way that leaves unmapped SKUs as themselves rather than turning them into `NaN` — that single mistake silently deletes most of the catalog.

In [93]:
# TODO
CANON = {
    'PT-12': 'POPTART-STRAW',
    'SKU#459812': 'POPTART-STRAW',
    'PT_STRAWBERRY': 'POPTART-STRAW'
}
cat['canonical'] = cat['sku'].map(CANON).fillna(cat['sku'])
cat

,sku,product_name,category,subcategory,unit_cost,supplier,package_size,canonical
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack,POPTART-STRAW
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk,POPTART-STRAW
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack,POPTART-STRAW
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack,POPTART-STRAW
4,WTR-24,BOTTLED WATER 24PK,Emergency Supplies,Bottled,2.64,Sara Lee,1 pack,WTR-24
5,WATER24PK,Bottled Water 24-Pack,Emergency,Bottled,2.38,Sara Lee,24 pack,WATER24PK
6,WTR_24PK,Water - 24 Pack,Emergency,NaN,2.08,Frito-Lay,1 pack,WTR_24PK
7,BATT-100,BATTERIES AA 4PK,Emergency Supplies,AA,NaN,3M Company,6 pack,BATT-100
8,BAT-AA4,AA Batteries 4-Pack,Emergency Supplies,AA,4.16,Kimberly-Clark,4pk,BAT-AA4
9,BATT_AA_4PK,AA Batteries 4-Pack,Emergency,AA,3.71,Anheuser-Busch,24 pack,BATT_AA_4PK
10,FLASH-01,FLASHLIGHT LED,Emergency,Flashlight,NaN,Frito-Lay,6-pack,FLASH-01
11,LED-FLASH,FLASHLIGHT LED,EMERGENCY,NaN,8.20,Frito-Lay,single,LED-FLASH
12,BEER-24,Light Beer (24-pack),Alcoholic Beverages,NaN,9.62,Hasbro,bundle,BEER-24
13,LTBEER24,Light Beer (24-pack),ALCOHOL,Light,7.61,Kellogg's,bundle,LTBEER24
14,BG-MONO,Monopoly Board Game,ENTERTAINMENT,NaN,9.96,Kimberly-Clark,1pk,BG-MONO
15,MONOPOLY-01,Monopoly Board Game,entertainment,NaN,12.51,Georgia-Pacific,24-pack,MONOPOLY-01
16,GAME-MONO,Board Game - Monopoly,ENTERTAINMENT,NaN,NaN,Campbell's,1pk,GAME-MONO
17,CARDS-01,Playing Cards,ENTERTAINMENT,Playing,2.45,J.M. Smucker,4pk,CARDS-01
18,PLAYCARD-STD,PLAYING CARDS,entertainment,Playing,2.39,Georgia-Pacific,24-pack,PLAYCARD-STD
19,STREAM-01,Roku Streaming Stick,Electronics,Streaming,16.70,3M Company,12 pack,STREAM-01
20,ROKU-STD,Streaming Device,electronics,Streaming,16.99,Anheuser-Busch,12 pack,ROKU-STD
21,SOUP-CAN,Soup - Canned,Groceries,Canned,1.23,J.M. Smucker,single,SOUP-CAN
22,CNSOUP-01,Canned Soup,GROCERY,NaN,1.19,Generic Supplier,single,CNSOUP-01
23,BREAD-WH,WHITE BREAD,Grocery,Bread,1.53,Procter & Gamble,24-pack,BREAD-WH
24,WHITEBREAD,WHITE BREAD,grocery,Bread,1.12,Sara Lee,24 pack,WHITEBREAD
25,PB-16,PEANUT BUTTER,GROCERY,Peanut,1.36,Hasbro,bundle,PB-16
26,PNUTBTR-16,Peanut Butter,GROCERY,Peanut,1.94,Sara Lee,1-pack,PNUTBTR-16
27,CNDL-EM,Candles (Emergency),EMERGENCY,Candles,3.81,Frito-Lay,1 pack,CNDL-EM
28,CANDLE-EMRG,Emergency Candles,EMERGENCY,Candles,3.43,Roku Inc,24pk,CANDLE-EMRG
29,FAID-01,First-Aid Kit,health,First,6.90,Anheuser-Busch,4 pack,FAID-01
30,FIRSTAID-KIT,First Aid Kit,health,NaN,7.85,J.M. Smucker,4 pack,FIRSTAID-KIT
31,CHRG-PORT,PORTABLE CHARGER,ELECTRONICS,NaN,11.99,Georgia-Pacific,single,CHRG-PORT
32,PORTCHARGER,Portable Phone Charger,ELECTRONICS,Portable,15.03,Johnson & Johnson,12 pack,PORTCHARGER
33,CHIPS-VP,Variety Pack - Chips,snacks,Chips,4.03,Frito-Lay,single,CHIPS-VP
34,CHIPVARIETY,Chips Variety Pack,Snacks,Chips,4.11,Generic Supplier,4-pack,CHIPVARIETY
35,PTOWEL-6,Paper Towels,household,Paper,3.85,Campbell's,4 pack,PTOWEL-6
36,PAPERTOWEL6,Paper Towels,HOUSEHOLD,Paper,5.09,Georgia-Pacific,12-pack,PAPERTOWEL6
37,TP-12,TOILET PAPER 12PK,household,Toilet,5.58,Campbell's,1 pack,TP-12
38,TOILETPAPER12,Toilet Paper 12-Roll,Household,Toilet,5.75,J.M. Smucker,24-pack,TOILETPAPER12
39,DIAP-S3,Baby Diapers - Size 3,baby,Diapers,14.40,Procter & Gamble,single,DIAP-S3
40,DIAPERS-3,DIAPERS SZ 3,Baby Products,Diapers,13.59,Generic Supplier,6 pack,DIAPERS-3
41,BFORM-01,Infant Formula,Baby,Baby,18.87,Procter & Gamble,4-pack,BFORM-01
42,BABYFORMULA,Baby Formula,Baby,NaN,18.25,Sara Lee,6 pack,BABYFORMULA
43,TARP-HD,Heavy Duty Tarp,Emergency,NaN,11.90,J.M. Smucker,12 pack,TARP-HD
44,HDTARP-01,TARP - HEAVY DUTY,emergency,Tarp,NaN,J.M. Smucker,24pk,HDTARP-01

### Q4 — Normalize `category`

Strip and title-case, then show the distinct values before and after with counts. Note any pair that is still two labels for one thing — `Breakfast` and `Breakfast Foods` are not the same string but they are the same category.

In [94]:
print("BEFORE")
print(len(cat['category']))
cat['category'].value_counts()

BEFORE
45

category
Emergency              5
Emergency Supplies     3
EMERGENCY              3
ENTERTAINMENT          3
GROCERY                3
Breakfast              2
entertainment          2
household              2
ELECTRONICS            2
health                 2
Baby                   2
Electronics            1
ALCOHOL                1
Alcoholic Beverages    1
breakfast              1
Breakfast Foods        1
Groceries              1
Grocery                1
electronics            1
snacks                 1
grocery                1
HOUSEHOLD              1
Snacks                 1
Household              1
baby                   1
Baby Products          1
emergency              1
Name: count, dtype: int64

In [95]:
# TODO
print("AFTER")
cat['category'] = cat['category'].str.strip().str.title()
print(len(cat['category']))
cat['category'].value_counts()

AFTER
45

category
Emergency              9
Entertainment          5
Grocery                5
Electronics            4
Household              4
Emergency Supplies     3
Breakfast              3
Baby                   3
Snacks                 2
Health                 2
Breakfast Foods        1
Alcohol                1
Alcoholic Beverages    1
Groceries              1
Baby Products          1
Name: count, dtype: int64

### Q5 — Find the fragmentation you have not spotted yet

Hand-scanning a catalog does not scale. **TODO:** build a candidate list programmatically — normalize each product name (lowercase, strip punctuation, sort the words) and group by that, then show any group holding more than one SKU.

This is the workflow from Monday's lecture, and it is how you will actually approach the full catalog on the midterm.

In [96]:
# TODO
category = cat.copy()
category['canonical'] = (category['product_name'].str.lower()
                         .str.replace(r'[^a-z ]', '', regex=True)
                         .str.split().apply(lambda w: ' '.join(sorted(w))))

candidates = (category.groupby('canonical')['sku']
              .agg(list).loc[lambda s: s.str.len() > 1])
candidates

canonical
aa batteries pack                     [BAT-AA4, BATT_AA_4PK]
beer light pack                          [BEER-24, LTBEER24]
board game monopoly        [BG-MONO, MONOPOLY-01, GAME-MONO]
bread white                           [BREAD-WH, WHITEBREAD]
butter peanut                            [PB-16, PNUTBTR-16]
candles emergency                     [CNDL-EM, CANDLE-EMRG]
canned soup                            [SOUP-CAN, CNSOUP-01]
cards playing                       [CARDS-01, PLAYCARD-STD]
chips pack variety                   [CHIPS-VP, CHIPVARIETY]
duty heavy tarp                         [TARP-HD, HDTARP-01]
flashlight led                         [FLASH-01, LED-FLASH]
paper towels                         [PTOWEL-6, PAPERTOWEL6]
poptarts strawberry    [PT-12, POPTART-STRAW, PT_STRAWBERRY]
Name: sku, dtype: object

### Q6 — Prove the mapping is safe

**TODO:** assert that applying your mapping produced no nulls in the canonical column and did not change the number of rows. Consolidation renames; it never adds or removes.

In [97]:
# TODO
assert category['canonical'].notna().all()
assert len(category) == len(cat)
category

,sku,product_name,category,subcategory,unit_cost,supplier,package_size,canonical
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack,poptarts strawberry
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk,poptart strawberry
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack,poptarts strawberry
3,PT_STRAWBERRY,pop-tarts strawberry,Breakfast,Pop-Tarts,NaN,Campbell's,4 pack,poptarts strawberry
4,WTR-24,BOTTLED WATER 24PK,Emergency Supplies,Bottled,2.64,Sara Lee,1 pack,bottled pk water
5,WATER24PK,Bottled Water 24-Pack,Emergency,Bottled,2.38,Sara Lee,24 pack,bottled pack water
6,WTR_24PK,Water - 24 Pack,Emergency,NaN,2.08,Frito-Lay,1 pack,pack water
7,BATT-100,BATTERIES AA 4PK,Emergency Supplies,AA,NaN,3M Company,6 pack,aa batteries pk
8,BAT-AA4,AA Batteries 4-Pack,Emergency Supplies,AA,4.16,Kimberly-Clark,4pk,aa batteries pack
9,BATT_AA_4PK,AA Batteries 4-Pack,Emergency,AA,3.71,Anheuser-Busch,24 pack,aa batteries pack
10,FLASH-01,FLASHLIGHT LED,Emergency,Flashlight,NaN,Frito-Lay,6-pack,flashlight led
11,LED-FLASH,FLASHLIGHT LED,Emergency,NaN,8.20,Frito-Lay,single,flashlight led
12,BEER-24,Light Beer (24-pack),Alcoholic Beverages,NaN,9.62,Hasbro,bundle,beer light pack
13,LTBEER24,Light Beer (24-pack),Alcohol,Light,7.61,Kellogg's,bundle,beer light pack
14,BG-MONO,Monopoly Board Game,Entertainment,NaN,9.96,Kimberly-Clark,1pk,board game monopoly
15,MONOPOLY-01,Monopoly Board Game,Entertainment,NaN,12.51,Georgia-Pacific,24-pack,board game monopoly
16,GAME-MONO,Board Game - Monopoly,Entertainment,NaN,NaN,Campbell's,1pk,board game monopoly
17,CARDS-01,Playing Cards,Entertainment,Playing,2.45,J.M. Smucker,4pk,cards playing
18,PLAYCARD-STD,PLAYING CARDS,Entertainment,Playing,2.39,Georgia-Pacific,24-pack,cards playing
19,STREAM-01,Roku Streaming Stick,Electronics,Streaming,16.70,3M Company,12 pack,roku stick streaming
20,ROKU-STD,Streaming Device,Electronics,Streaming,16.99,Anheuser-Busch,12 pack,device streaming
21,SOUP-CAN,Soup - Canned,Groceries,Canned,1.23,J.M. Smucker,single,canned soup
22,CNSOUP-01,Canned Soup,Grocery,NaN,1.19,Generic Supplier,single,canned soup
23,BREAD-WH,WHITE BREAD,Grocery,Bread,1.53,Procter & Gamble,24-pack,bread white
24,WHITEBREAD,WHITE BREAD,Grocery,Bread,1.12,Sara Lee,24 pack,bread white
25,PB-16,PEANUT BUTTER,Grocery,Peanut,1.36,Hasbro,bundle,butter peanut
26,PNUTBTR-16,Peanut Butter,Grocery,Peanut,1.94,Sara Lee,1-pack,butter peanut
27,CNDL-EM,Candles (Emergency),Emergency,Candles,3.81,Frito-Lay,1 pack,candles emergency
28,CANDLE-EMRG,Emergency Candles,Emergency,Candles,3.43,Roku Inc,24pk,candles emergency
29,FAID-01,First-Aid Kit,Health,First,6.90,Anheuser-Busch,4 pack,firstaid kit
30,FIRSTAID-KIT,First Aid Kit,Health,NaN,7.85,J.M. Smucker,4 pack,aid first kit
31,CHRG-PORT,PORTABLE CHARGER,Electronics,NaN,11.99,Georgia-Pacific,single,charger portable
32,PORTCHARGER,Portable Phone Charger,Electronics,Portable,15.03,Johnson & Johnson,12 pack,charger phone portable
33,CHIPS-VP,Variety Pack - Chips,Snacks,Chips,4.03,Frito-Lay,single,chips pack variety
34,CHIPVARIETY,Chips Variety Pack,Snacks,Chips,4.11,Generic Supplier,4-pack,chips pack variety
35,PTOWEL-6,Paper Towels,Household,Paper,3.85,Campbell's,4 pack,paper towels
36,PAPERTOWEL6,Paper Towels,Household,Paper,5.09,Georgia-Pacific,12-pack,paper towels
37,TP-12,TOILET PAPER 12PK,Household,Toilet,5.58,Campbell's,1 pack,paper pk toilet
38,TOILETPAPER12,Toilet Paper 12-Roll,Household,Toilet,5.75,J.M. Smucker,24-pack,paper roll toilet
39,DIAP-S3,Baby Diapers - Size 3,Baby,Diapers,14.40,Procter & Gamble,single,baby diapers size
40,DIAPERS-3,DIAPERS SZ 3,Baby Products,Diapers,13.59,Generic Supplier,6 pack,diapers sz
41,BFORM-01,Infant Formula,Baby,Baby,18.87,Procter & Gamble,4-pack,formula infant
42,BABYFORMULA,Baby Formula,Baby,NaN,18.25,Sara Lee,6 pack,baby formula
43,TARP-HD,Heavy Duty Tarp,Emergency,NaN,11.90,J.M. Smucker,12 pack,duty heavy tarp
44,HDTARP-01,TARP - HEAVY DUTY,Emergency,Tarp,NaN,J.M. Smucker,24pk,duty heavy tarp

### Write-up

**a)** Name two product families beyond Pop-Tarts that appear fragmented, and how you would group them.

Bottled water in a 24 pack is also fragmented. I grouped them based on those that were in a 24 pack. If it was a different size, then that would be a different product. Also, chip variety pack has different SKUs that were fragemented. They have now been combine

**b)** Where does consolidation stop being a data-cleaning task and become a business decision? Give one example from this catalog where you genuinely are not sure, and say who you would ask.

It depends on when you want to consolidate products as the same or not. For example, a different size of bottled water may be better to keep distinguish. There may be more information on what size of water packs people are more likely to buy depending on the season. You would lose this information if the products were grouped.

_your answer here_